local keymap = vim.api.nvim_set_keymap
local options = { noremap = true }
keymap('n', 'gd', ':lua vim.lsp.buf.definition()<cr>', options)
keymap('n', 'gD', ':lua vim.lsp.buf.declaration()<cr>', options)
keymap('n', 'gi', ':lua vim.lsp.buf.implementation()<cr>', options)
keymap('n', 'gw', ':lua vim.lsp.buf.document_symbol()<cr>', options)
keymap('n', 'gw', ':lua vim.lsp.buf.workspace_symbol()<cr>', options)
keymap('n', 'gr', ':lua vim.lsp.buf.references()<cr>', options)
keymap('n', 'gt', ':lua vim.lsp.buf.type_definition()<cr>', options)
keymap('n', 'K', ':lua vim.lsp.buf.hover()<cr>', options)
keymap('n', '<c-k>', ':lua vim.lsp.buf.signature_help()<cr>', options)
keymap('n', '<leader>af', ':lua vim.lsp.buf.code_action()<cr>', options)
keymap('n', '<leader>rn', ':lua vim.lsp.buf.rename()<cr>', options)
keymap('n', '<leader>a', ':lua vim.diagnostic.goto_next()<cr>', options)
keymap('n', '<leader>e', ':NvimTreeToggle<cr>', options)
keymap('n', '<leader>w', ':w<cr>', options)
keymap('n', '<leader>o', ':ls<cr>', options)
keymap('n', '<space>', '/', options)
